### PR TITLE
Added an Example of Rock-Paper-Scissor App in Flutter

### PR DESCRIPTION
**Pull request by sayannath**
Hi @margaretmz mam. I hope you are doing well. I have added an example app on Rock-Paper and Scissor where I made the model with CNN architecture and then applied Quantisation Aware Training and deployed that in a Flutter App. I have also linked the notebook link as well. I have also linked the notebook of American Sign Language Detection.

Thank You

### CODE REVIEW

**Comment by margaretmz** [comment]
Double check your PR - I don't see the Flutter app. Just saw a few changes to the American Sign Language Detection. Suggest create separate PR per change (Rock-Paper-Scissor Flutter app vs American Sign Language Detection). Thanks.

**Comment by sayannath** [comment]
Hi @margaretmz 
I have made the changes.

**Comment by neso613** [comment]
Hi @margaretmz 
I am also willing to contribute here. The provided contribution.md  is confusing for me.
Can you tell me the structure so that I can make a PR.
Thanks!

**Comment by sayannath** [comment]
> Hi @margaretmz
> I am also willing to contribute here. The provided contribution.md is confusing for me.
> Can you tell me the structure so that I can make a PR.
> Thanks!

You enlist your work here in a table format.

**Review by margaretmz — APPROVED** [review]

**Comment by neso613** [comment]
> Hi @margaretmz
> I am also willing to contribute here. The provided contribution.md is confusing for me.
> Can you tell me the structure so that I can make a PR.
> Thanks!

Hi @sayannath 
can you help me pls

**Comment by sayannath** [comment]
> > Hi @margaretmz
> > I am also willing to contribute here. The provided contribution.md is confusing for me.
> > Can you tell me the structure so that I can make a PR.
> > Thanks!
> 
> Hi @sayannath
> can you help me pls

Yes, sure! you just have to make an application that uses tflite.

**Pull request merged**
