### PR TITLE
Add "TensorFlow Lite Examples - Android" in Helpful links

### PR DESCRIPTION
**Pull request by dailystudio**
This link directs to a repository that refactors and rewrites all the TensorFlow Lite examples included in the TensorFlow official website.  It helps you easily understand how does a captured Bitmap, a small buffer of raw audio data, or a piece of text convert run in inference and how to represent those results on the user interface.

### CODE REVIEW

**Comment by margaretmz** [comment]
@dailystudio, thanks for your PR! Would it makes more sense for you to help improve the existing official examples instead of creating your own repo for it: [https://github.com/dailystudio/tensorflow-lite-examples-android](https://github.com/dailystudio/tensorflow-lite-examples-android)? It wouldn't be a very good user experience if a developer needs to look at 2 different repos for the exact same sample.

@khanhlvg what are your thoughts on this?

**Comment by dailystudio** [comment]
> @dailystudio, thanks for your PR! Would it makes more sense for you to help improve the existing official examples instead of creating your own repo for it: https://github.com/dailystudio/tensorflow-lite-examples-android? It wouldn't be a very good user experience if a developer needs to look at 2 different repos for the exact same sample.
> 
> @khanhlvg what are your thoughts on this?

I agree with you. And your suggestion is what I was thinking at the beginning. But, finally, I gave up. I found that existing official examples are a  little bit messy. They are maintained by different people with different acknowledgment of Android development. The project layouts are quite different. It is much easier to rewrite than refactor. So I created a new repo. 

I contacted some guys in Google and they suggested me to post a PR here.  I think my work might not be aligned with their short-term roadmap or it is a bit difficult to be merged with existing code. I think your project might be the better place to show my work and help others to understand the latest TFLite updates effectively.

**Comment by khanhlvg** [comment]
I agree that there's some inconsistency between different Android apps in the TFLite official sample repos as there're some historical issues around it. However, it isn't easy to revamp the apps with the community as there are several internal infrastructure depends on the current samples.

Therefore, I think it makes sense to have @dailystudio hosts his rebuilt samples on his own repo and link it here as one of the community project.

**Comment by margaretmz** [comment]
@dailystudio and @khanhlvg, thank you both for your input! I merged the PR.

**Pull request merged**
